import { Ingredient } from "../components/burger-ingredients/lib/types";

export const mockData: Ingredient[] = [
  {
    _id: "60666c42cc7b410027a1a9b1",
    name: "Краторная булка N-200i",
    type: "bun",
    proteins: 80,
    fat: 24,
    carbohydrates: 53,
    calories: 420,
    price: 1255,
    image: require("../images/bun_crater.png"),
    image_mobile: require("../images/bun_crater.png"),
    image_large: require("../images/bun_crater.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9b5",
    name: "Говяжий метеорит (отбивная)",
    type: "main",
    proteins: 800,
    fat: 800,
    carbohydrates: 300,
    calories: 2674,
    price: 3000,
    image: require("../images/meat_meteor.png"),
    image_mobile: require("../images/meat_meteor.png"),
    image_large: require("../images/meat_meteor.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9b6",
    name: "Биокотлета из марсианской Магнолии",
    type: "main",
    proteins: 420,
    fat: 142,
    carbohydrates: 242,
    calories: 4242,
    price: 424,
    image: require("../images/meat_bio.png"),
    image_mobile: require("../images/meat_bio.png"),
    image_large: require("../images/meat_bio.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9b7",
    name: "Соус Spicy-X",
    type: "sauce",
    proteins: 30,
    fat: 20,
    carbohydrates: 40,
    calories: 30,
    price: 90,
    image: require("../images/sauce_spicy.png"),
    image_mobile: require("../images/sauce_spicy.png"),
    image_large: require("../images/sauce_spicy.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9b4",
    name: "Мясо бессмертных моллюсков Protostomia",
    type: "main",
    proteins: 433,
    fat: 244,
    carbohydrates: 33,
    calories: 420,
    price: 1337,
    image: require("../images/meat_mollusc.png"),
    image_mobile: require("../images/meat_mollusc.png"),
    image_large: require("../images/meat_mollusc.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9b9",
    name: "Соус традиционный галактический",
    type: "sauce",
    proteins: 42,
    fat: 24,
    carbohydrates: 42,
    calories: 99,
    price: 15,
    image: require("../images/sauce_traditional.png"),
    image_mobile: require("../images/sauce_traditional.png"),
    image_large: require("../images/sauce_traditional.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9b8",
    name: "Соус фирменный Space Sauce",
    type: "sauce",
    proteins: 50,
    fat: 22,
    carbohydrates: 11,
    calories: 14,
    price: 80,
    image: require("../images/sauce_space.png"),
    image_mobile: require("../images/sauce_space.png"),
    image_large: require("../images/sauce_space.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9bc",
    name: "Плоды Фалленианского дерева",
    type: "main",
    proteins: 20,
    fat: 5,
    carbohydrates: 55,
    calories: 77,
    price: 874,
    image: require("../images/plant.png"),
    image_mobile: require("../images/plant.png"),
    image_large: require("../images/plant.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9bb",
    name: "Хрустящие минеральные кольца",
    type: "main",
    proteins: 808,
    fat: 689,
    carbohydrates: 609,
    calories: 986,
    price: 300,
    image: require("../images/mineral_rings.png"),
    image_mobile: require("../images/mineral_rings.png"),
    image_large: require("../images/mineral_rings.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9ba",
    name: "Соус с шипами Антарианского плоскоходца",
    type: "sauce",
    proteins: 101,
    fat: 99,
    carbohydrates: 100,
    calories: 100,
    price: 88,
    image: require("../images/sauce_spike.png"),
    image_mobile: require("../images/sauce_spike.png"),
    image_large: require("../images/sauce_spike.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9bd",
    name: "Кристаллы марсианских альфа-сахаридов",
    type: "main",
    proteins: 234,
    fat: 432,
    carbohydrates: 111,
    calories: 189,
    price: 762,
    image: require("../images/crystal.png"),
    image_mobile: require("../images/crystal.png"),
    image_large: require("../images/crystal.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9be",
    name: "Мини-салат Экзо-Плантаго",
    type: "main",
    proteins: 1,
    fat: 2,
    carbohydrates: 3,
    calories: 6,
    price: 4400,
    image: require("../images/mini_salat.png"),
    image_mobile: require("../images/mini_salat.png"),
    image_large: require("../images/mini_salat.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9b3",
    name: "Филе Люминесцентного тетраодонтимформа",
    type: "main",
    proteins: 44,
    fat: 26,
    carbohydrates: 85,
    calories: 643,
    price: 988,
    image: require("../images/meat_luminous.png"),
    image_mobile: require("../images/meat_luminous.png"),
    image_large: require("../images/meat_luminous.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9bf",
    name: "Сыр с астероидной плесенью",
    type: "main",
    proteins: 84,
    fat: 48,
    carbohydrates: 420,
    calories: 3377,
    price: 4142,
    image: require("../images/cheese.png"),
    image_mobile: require("../images/cheese.png"),
    image_large: require("../images/cheese.png"),
    __v: 0,
  },
  {
    _id: "60666c42cc7b410027a1a9b2",
    name: "Флюоресцентная булка R2-D3",
    type: "bun",
    proteins: 44,
    fat: 26,
    carbohydrates: 85,
    calories: 643,
    price: 988,
    image: require("../images/bun_fluo.png"),
    image_mobile: require("../images/bun_fluo.png"),
    image_large: require("../images/bun_fluo.png"),
    __v: 0,
  },
];
